// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYIuqFQdgbZ2qMYcBT6RK5q3XGWS2cuKc',
    appId: '1:450293350174:web:e505f01c517de94d9f930f',
    messagingSenderId: '450293350174',
    projectId: 'stepmeet-8ed5d',
    authDomain: 'stepmeet-8ed5d.firebaseapp.com',
    storageBucket: 'stepmeet-8ed5d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz_txhHE4AKenknZcphkhLnpZOavvJH80',
    appId: '1:450293350174:android:14679d24623adff49f930f',
    messagingSenderId: '450293350174',
    projectId: 'stepmeet-8ed5d',
    storageBucket: 'stepmeet-8ed5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA36OtyX47B4tRR_YFNWShDQ52_mQ2romM',
    appId: '1:450293350174:ios:c1e4fed36c4a8ca69f930f',
    messagingSenderId: '450293350174',
    projectId: 'stepmeet-8ed5d',
    storageBucket: 'stepmeet-8ed5d.appspot.com',
    iosBundleId: 'com.example.finalProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA36OtyX47B4tRR_YFNWShDQ52_mQ2romM',
    appId: '1:450293350174:ios:6cbfc3c54a107e949f930f',
    messagingSenderId: '450293350174',
    projectId: 'stepmeet-8ed5d',
    storageBucket: 'stepmeet-8ed5d.appspot.com',
    iosBundleId: 'com.example.finalProject1.RunnerTests',
  );
}
